spring.application.name=capyjet-backend

spring.datasource.url=jdbc:postgresql://localhost:5432/capyjet
spring.datasource.username=capyjet
spring.datasource.password=capyjet

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.open-in-view=false
